### ISSUE TITLE
Extra blank line

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-script#145]
There is an extra blank line at the end of `canonical-livepatch status` that we should probably suppress:
```
ubuntu@xenial-cc:~$ canonical-livepatch status;echo hi there
client-version: 8.0.2
architecture: x86_64
cpu-model: QEMU Virtual CPU version 2.5+
last-check: 2018-06-18T14:39:29.510657262Z
boot-time: 2018-06-18T13:36:48Z
uptime: 1h5m53s
status:
- kernel: 4.4.0-128.154-generic
  running: true
  livepatch:
    checkState: checked
    patchState: nothing-to-apply
    version: ""
    fixes: ""

hi there
```
It becomes problematic once other services start printing their status after livepatch:
```
esm: disabled (not available)
fips: disabled
livepatch: enabled
  client-version: 8.0.2
  architecture: x86_64
  cpu-model: QEMU Virtual CPU version 2.5+
  last-check: 2018-06-18T14:39:29.510657262Z
  boot-time: 2018-06-18T13:36:48Z
  uptime: 1h6m31s
  status:
  - kernel: 4.4.0-128.154-generic
    running: true
    livepatch:
      checkState: checked
      patchState: nothing-to-apply
      version: ""
      fixes: ""
  
cc: enabled
  cc: artifacts are in /usr/lib/common-criteria
ubuntu@xenial-cc:~$ 
```
